### ISSUE TITLE
How to load a previously saved vector database?

### ISSUE THREAD

**Issue by luludus** [awa-ai/awadb#13]
I save the text vector using the following code:

`vector_store = AwaDB.from_documents(docs,self.embeddings,
                                                    table_name="langchain_awadb",log_and_data_dir = vs_path)`

When I want to reload the vector database before the vs_path path, I try the load() function and load_local() function, but both of them  return a value of type bool. 
How can I reload the previously saved vector database?

**Comment by ljeagle** [comment]
if the load_local() return true, means reloading success, otherwise fail. 
the vector database client is used the same

**Comment by luludus** [comment]
> 

Thanks for you reply. when I use load_local(), how do i init a AwaDB class?
I use the code: 
`vector_store = AwaDB("langchain_awadb",self.embeddings, vs_path)
            ret = vector_store.load_local("langchain_awadb")`
the ret is False

**Comment by luludus** [comment]
> > 
> 
> Thanks for you reply. when I use load_local(), how do i init a AwaDB class? I use the code: `vector_store = AwaDB("langchain_awadb",self.embeddings, vs_path) ret = vector_store.load_local("langchain_awadb")` the ret is False

I‘m Sorry. There was a problem in my code, the table_name I created later was the same as before so it failed to load.

**Comment by ljeagle** [comment]
OK
