### ISSUE TITLE
Add function error faced when using inside a for loop

### ISSUE THREAD

**Issue by taozhiwang** [awa-ai/awadb#32]
I've noticed that when I use the Add function in a for loop, python crashes and reports an error.

```python
print(texts)

awadb_client = awadb.Client()
awadb_client.Create("testdb1")


for text in texts:
    print([text])
    awadb_client.Add([text])
```
The code that led me to this error was as above.
Here are the error information:
```
[1]    82822 trace trap  /opt/homebrew/bin/python3 
```
I use `python 3.11.4` and `awadb 0.3.9`. 

Here are parts of the variables' information:
`texts` is a list of string.
`[text]` is a list which only contain one string.

**Comment by ljeagle** [comment]
Could you give a detailed test codes?

**Comment by taozhiwang** [comment]
Sure! I can only upload `.zip` file. The following file is what I used to test.

`test.py` is the test file 
`test.log` is the log information for this test

[Archive.zip](https://github.com/awa-ai/awadb/files/12331506/Archive.zip)
